server:
  port: 8005

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.101.26:3306/db2020?characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: 123456
  cloud:
    consul:
      host: 192.168.101.26
      port: 8500
      discovery:
        service-name: consul-provider-payment
        heartbeat:
          enabled: true
          
management:
  endpoint:
    health:
      show-details: always

mybatis:
  # 实体类扫描
  type-aliases-package: com.qhm.springcloud.entities
  # 配置映射文件位置
  mapper-locations: classpath:mapper/*.xml

myconfig:
  swagger-ui-open: true
  